-- CREATE TABLE FLOOR_CONNECTORS
CREATE TABLE IF NOT EXISTS floor_connectors(
  id INT UNIQUE NOT NULL,
  name VARCHAR(255),
  type INT NOT NULL DEFAULT 0, --staircase
  requires_auth BOOLEAN NOT NULL DEFAULT FALSE,
  is_operational BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY fk_node2(id)
  REFERENCES nodes(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);
