-- CREATE TABLE NODES
CREATE TABLE IF NOT EXISTS nodes(
  id INT UNIQUE NOT NULL AUTO_INCREMENT,
  building INT NOT NULL,
  x DECIMAL NOT NULL DEFAULT 0,
  y DECIMAL NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CHECK (x >= 0),
  CHECK (y >= 0)
);
