-- CREATE THE ROOM TABLE
CREATE TABLE IF NOT EXISTS rooms(
  id INT UNIQUE NOT NULL,
  room_num VARCHAR(50) UNIQUE,
  name VARCHAR(255),
  requires_auth BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY fk_node1(id)
  REFERENCES nodes(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT,
  CHECK (x >= 0),
  CHECK (y >= 0)
);
